### ISSUE TITLE
.check_suite.yml now named .checks.yml ?

### ISSUE THREAD

**Issue by hartwork** [LambdaLint/demo#8]
According to https://fussyfox.github.io/ I'd expect `.check_suite.yml` to be named `.checks.yml`, instead. Is a rename pending?

**Comment by codingjoe** [comment]
Hi @hartwork,

they might be support for more names coming up. Where did you find a reference for `.check_suite.yml`?

**Comment by hartwork** [comment]
Right in here: https://github.com/FussyFox/demo/blob/258d8282e7a76d76fad54a5e169040f5501c8799/.check_suite.yml#L1-L3

**Comment by codingjoe** [comment]
haha, good point, thx
